export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAIL = 'GET_ORDERS_FAIL';

export const SET_ORDER_STATUS_SUCCESS = 'SET_ORDER_STATUS_SUCCESS';
export const SET_ORDER_STATUS_FAIL = 'SET_ORDER_STATUS_FAIL';
