export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';

export const SAVE_CART_SUCCESS = 'SAVE_CART_SUCCESS';
export const SAVE_CART_FAIL = 'SAVE_CART_FAIL';

export const GET_CART_SUCCESS = 'GET_CART_SUCCESS';
export const GET_CART_FAIL = 'GET_CART_FAIL';
export const GET_CART_RESET = 'GET_CART_RESET';

export const APPLY_COUPON_TO_CART_SUCCESS = 'APPLY_COUPON_TO_CART_SUCCESS';
export const APPLY_COUPON_TO_CART_FAIL = 'APPLY_COUPON_TO_CART_FAIL';
export const APPLY_COUPON_TO_CART_RESET = 'APPLY_COUPON_TO_CART_RESET';