export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS';
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL';

export const CREATE_CASH_ORDER_SUCCESS = 'CREATE_CASH_ORDER_SUCCESS';
export const CREATE_CASH_ORDER_FAIL = 'CREATE_CASH_ORDER_FAIL';
