export const CREATE_PRODUCT_SUCCESS = 'CREATE_PRODUCT_SUCCESS';
export const CREATE_PRODUCT_FAIL = 'CREATE_PRODUCT_FAIL';
export const CREATE_PRODUCT_RESET = 'CREATE_PRODUCT_RESET';

export const GET_PRODUCTS_LIMIT_SUCCESS = 'GET_PRODUCTS_LIMIT_SUCCESS';
