export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const LOGOUT = 'LOGOUT';

export const SAVE_USER_ADDRESS_SUCCESS = 'SAVE_USER_ADDRESS_SUCCESS';
export const SAVE_USER_ADDRESS_FAIL = 'SAVE_USER_ADDRESS_FAIL';
